export enum UIName {
    HUDView = "ui/HUDView",

    MainUI = "ui/MainUI",
    RookieGuide = "ui/RookieGuide",
    DialogueUI = "ui/DialogueUI",
    SecretGuardGettedUI = "ui/SecretGuardGettedUI",
    TreasureGettedUI = "ui/TreasureGettedUI",
    TaskListUI = "ui/TaskListUI",
    BuildingUpgradeUI = "ui/BuildingUpgradeUI",
    RecruitUI = "ui/RecruitUI",
    TransformToEnergyUI = "ui/TransformToEnergyUI",
    BrachEventUI = "ui/BrachEventUI",
    CivilizationLevelUpUI = "ui/CivilizationLevelUpUI",
    PlayerInfoUI = "ui/PlayerInfoUI",
    NewSettlementUI = "ui/NewSettlementUI",
    Backpack = "ui/Backpack",
    ItemInfoUI = "ui/ItemInfoUI",
    ItemSelectFromThreeUI = "ui/ItemSelectFromThreeUI",
    BattleReportUI = "ui/BattleReportUI",
    LootsPopup = "ui/LootsPopup",
    Artifact = "ui/Artifact",
    ArtifactInfoUI = "ui/ArtifactInfoUI",
}