export enum NotificationName {
    CONFIG_LOADED = 100,
    GAME_INITED,
    USER_LOGIN_SUCCEED,

    CHANGE_CURSOR,
    GAME_CAMERA_POSITION_CHANGED,
    GAME_CAMERA_ZOOM_CHANGED,
    GAME_INNER_AND_OUTER_CHANGED,
    GAME_INNER_BUILDING_LATTICE_EDIT_CHANGED,
    GAME_INNER_LATTICE_EDIT_ACTION_MOUSE_DOWN,
    GAME_INNER_LATTICE_EDIT_ACTION_MOUSE_UP,
    GAME_INNER_LATTICE_EDIT_ACTION_MOUSE_MOVE,

    RESOURCE_GETTED,
    RESOURCE_CONSUMED,

    GENERATE_ENERGY_TIME_COUNT_CHANGED,
    GENERATE_ENERGY_NUM_CHANGED,

    INNER_BUILDING_BEGIN_UPGRADE,
    INNER_BUILDING_UPGRADE_COUNT_TIME_CHANGED,
    INNER_BUILDING_UPGRADE_FINISHED,

    // language
    CHANGE_LANG,

    // MainBuildUpgrade
    MAIN_BUILD_LEVEL_UP,

    FIGHT_FINISHED,
    MINING_FINISHED,

    // rookie guide
    ROOKIE_GUIDE_BEGIN_EYES,
    ROOKIE_GUIDE_THIRD_EYES,
    ROOKIE_GUIDE_END_PIONEER_WAKE_UP,

    // artifact
    ARTIFACT_CHANGE,

    // item
    ITEM_CHANGE,

    // event
    EVENT_STEPEND,

    // BattleReport
    BATTLE_REPORT_LIST_CHANGED,

    GENERATE_TROOP_TIME_COUNT_ChANGED,
    GENERATE_TROOP_NUM_CHANGED,

    //---------------------- task
    TASK_CANNOTGET,
    TASK_NEW_GETTED,
    TASK_FAILED,
    TASK_STEP_FINISHED,
    TASK_FINISHED,
    //---------------------- map member
    MAP_MEMBER_CHANGE_SHOW_HIDE,
    MAP_MEMBER_CHANGE_FACTION,

    MAP_PIONEER_GET_NEW_TALK,
    MAP_PIONEER_USE_NEW_TALK,
    MAP_PIONEER_NEW_TALK_GETTED,
    MAP_PIONEER_NEW_TALK_USED,
    MAP_PIONEER_SHOW_HIDE_COUNT_CHANGED,
    MAP_PIONEER_GET_TALK_COUNT_CHANGED,
    //---------------------- dialog
    DIALOG_SHOW,

    CHOOSE_GANGSTER_ROUTE,
}
